# user1 = User.create(name: "Jim", email: "jim@example.com", password: "password", image_url: "https://eu-images.contentstack.com/v3/assets/bltcd74acc1d0a99f3a/blt7e043b0e2a65262a/6351ab629149521049dd09b4/Screenshot_2022-10-20_at_21.10.55.png")

# user2 = User.create(name: "Matt", email: "matt@example.com", password: "password", image_url: "https://media.istockphoto.com/id/1311330212/photo/i-am-getting-better-day-by-day.jpg?s=612x612&w=0&k=20&c=YkAwI4j5dkYEC5bsqpdW5L7nwSPI-BsttHdQivrt6c8=")

# user3 = User.create(name: "Jane", email: "jane@example.com", password: "password", image_url: "https://thumbs.dreamstime.com/b/fitness-woman-shaker-gym-drinking-water-athletic-girl-shaped-abdominal-slim-waist-fitness-woman-shaker-gym-118631847.jpg")

# exercise1 = Exercise.create(name: "Bench Press", description: "The bench press is a compound exercise that targets the muscles of the upper body. It involves lying on a bench and pressing weight upward using either a barbell or a pair of dumbbells. During a bench press, you lower the weight down to chest level and then press upwards while extending your arms", image_url: "https://cdn.mos.cms.futurecdn.net/pLaRi5jXSHDKu6WRydetBo.jpg", video_url: "https://youtu.be/gRVjAtPip0Y")
# exercise2 = Exercise.create(name: "Incline Bench Press", description: "The incline bench press is a variation of the bench press and an exercise used to build the muscles of the chest. The shoulders and triceps will be indirectly involved as well. Lie flat on an incline bench and set your hands just outside of shoulder width. Set your shoulder blades by pinching them together and driving them into the bench. Take a deep breath and allow your spotter to help you with the lift off in order to maintain tightness through your upper back.
# Let the weight settle and ensure your upper back remains tight after lift off.
# Inhale and allow the bar to descend slowly by unlocking the elbows. Lower the bar in a straight line to the base of the sternum (breastbone) and touch the chest. Push the bar back up in a straight line by pressing yourself into the bench, driving your feet into the floor for leg drive, and extending the elbows.
# Repeat for the desired number of repetitions.", image_url: "https://cdn.muscleandstrength.com/sites/default/files/incline-bench-press.jpg", video_url: "https://www.muscleandstrength.com/exercises/incline-bench-press.html")
# exercise3 = Exercise.create(name: "Dumbbell Fly", description: "The dumbbell fly utilizes a chest fly movement pattern to isolate the muscles fo the chest to better help the muscles grow and become stronger. Pick up the dumbbells off the floor using a neutral grip (palms facing in). Position the ends of the dumbbells in your hip crease, and sit down on the bench. To get into position, lay back and keep the weights close to your chest. Once you are in position, take a deep breath, then press the dumbbells to lockout at the top. Slightly retract your shoulder blades, unlock your elbows, and slowly lower the dumbbells laterally while maintaining the angle at your elbow. Once the dumbbells reach chest level, reverse the movement by squeezing your pecs together and bringing the dumbbells back to their starting position. Without allowing the dumbbells to touch, start the next repetition, and continue until the set is completed.", image_url: "https://hips.hearstapps.com/hmg-prod/images/form-check-10-1554408283.png?crop=0.888888888888889xw:1xh;center,top", video_url: "https://www.youtube.com/watch?v=ul7j4OkNRq4")
# exercise4 = Exercise.create(name: "Shoulder Press", description: "The Shoulder Press is an upper body strength training movement, traditionally performed with dumbbells or a barbell. The weight is pressed vertically overhead", image_url: "https://cdn.shopify.com/s/files/1/1497/9682/articles/1_71d97192-f77f-47fa-a059-87456a2c1fb1.jpg?v=1647872386", video_url: "https://www.youtube.com/watch?v=0JfYxMRsUCQ")
# exercise5 = Exercise.create(name: "Dumbbell Lateral Raise", description: "The side lateral raise is an effective shoulder-strengthening movement designed to isolate the lateral head of the deltoid muscle. Performed regularly, this can help you develop stronger, broader shoulders. All you need is a pair of light dumbbells and enough shoulder flexibility to abduct your arms (lifting the weights out and away from your body) until they form a T shape at your shoulders.", image_url: "https://cdn.shopify.com/s/files/1/1497/9682/articles/1_22b6dc92-2f1d-49a0-be71-74631fbe3e55.jpg?v=1653913558", video_url: "https://www.youtube.com/watch?v=geenhiHju-o")
# exercise6 = Exercise.create(name: "Reverse Pec Deck Fly", description: "This shoulder exercise targets your posterior delts and requires a pec dec machine. It's also the perfect chest, back and shoulder workout for building mass. Face the machine, and position the seat so that the handles are at shoulder level on either side. Next, hold the handles with your palms facing inward. Tighten your torso and extend your arms out to the side, pushing through all the way.
# Responsibly return to the starting position. Repeat.", image_url: "https://musclemaker.com.au/wp-content/uploads/2020/08/How-to-do-reverse-peck-deck-fly.jpg", video_url: "https://www.youtube.com/watch?v=MOBQn99Z1T4") 
# exercise7 = Exercise.create(name: "Barbell Squat", description: "A barbell squat, also known as a barbell back squat, is a compound exercise that activates muscle groups throughout your lower body, including your hamstrings, glutes, and lower back muscles. Perform barbell squats by standing with your feet shoulder-width apart. Take a deep breath and unrack a weighted barbell, holding it on your upper back. Keep your chest up and your back straight as you hinge your hips and knees to lower your body through a full range of motion into a squat position.", image_url: "https://parade.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTk0MjYxNzc2MTM1NjI4NDY1/how-to-do-barbell-squat.jpg", video_url: "https://youtu.be/1oed-UmAxFs")
# exercise8 = Exercise.create(name: "Dumbbell Lunges", description: "Start with two dumbbells, one in each hand. Inhale and take a big step forward with your right leg, landing on the heel. Bend at the knee until the right thigh approaches parallel to the ground. The left leg is bent at the knee and balanced on the toes while in the lunge position. Step the right foot back on an exhale to return to the starting position. Repeat motion with right leg.", image_url: "https://cdn2.stylecraze.com/wp-content/uploads/2014/11/Walking-Lunges-With-Weight.jpg", video_url: "https://youtu.be/auyE2hZGB9k")
# exercise9 = Exercise.create(name: "Seated Leg Curl", description: "Seated leg curls is a gym workout that targets hamstrings and also involves glutes and hip flexors. Adjust the seated leg curl machine to position the footpad just above your heels. Sit upright and engage your abs as so you position your legs in front of you. Begin to curl your legs back slowly towards you and flex your calf muscles as you do so. Return to the starting position by extending the legs in front of you again.", image_url: "https://qph.cf2.quoracdn.net/main-qimg-116e6e5c31e0abaf146ec046f2409eab-lq", video_url: "https://www.youtube.com/watch?v=t9sTSr-JYSs")

# routine1 = user1.routines.create(name: "Chest Killer Workout", description: "A workout designed to kill your chest. R.I.P(Rest In Protein).")
# routine2 = user2.routines.create(name: "Shoulder Destroyer Workout", description: "Your shoulders will be begging for mercy after this high intensity workout!")
# routine3 = user3.routines.create(name: "Leg Obliterator Workout", description: "You won't be able to walk for weeks after this workout! And that's... a good thing.")

# routine1_exercise1 = routine1.routine_exercises.create(exercise: exercise1, reps: 8, sets: 4)
# routine1_exercise2 = routine1.routine_exercises.create(exercise: exercise2, reps: 10, sets: 3)
# routine1_exercise3 = routine1.routine_exercises.create(exercise: exercise3, reps: 12, sets: 3)

# routine2_exercise1 = routine2.routine_exercises.create(exercise: exercise4, reps: 6, sets: 4)
# routine2_exercise2 = routine2.routine_exercises.create(exercise: exercise5, reps: 15, sets: 3)
# routine2_exercise3 = routine2.routine_exercises.create(exercise: exercise6, reps: 12, sets: 3)

# routine3_exercise1 = routine3.routine_exercises.create(exercise: exercise7, reps: 8, sets: 4)
# routine3_exercise2 = routine3.routine_exercises.create(exercise: exercise8, reps: 12, sets: 3)
# routine3_exercise3 = routine3.routine_exercises.create(exercise: exercise9, reps: 15, sets: 3)